# SPDX-License-Identifier: MIT
---
- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

# Examples of some tasks:
- name: Deploy Trustee Server Components using Podman Quadlets
  include_tasks: trustee_quadlet.yml
  when: trustee_server_trustee | bool

- name: Deploy Secret Registration Server Service
  include_tasks: secret_registration_server.yml
  when:
    - trustee_server_secret_registration_enabled | bool
    - trustee_server_trustee | bool
